// src/app/layout.tsx
import Providers from "./Provider"; // <-- Import the component
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers> {/* <-- Wrap your children */}
      </body>
    </html>
  );
}